passagens/urls.py
from django.urls import path
from . import views

app_name = 'passagens'
urlpatterns = [
    path('', views.index, name='home'),
    path('detalhes/', views.detalhes, name='detalhes'),
]

validandoFormularios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('passagens.urls', namespace='passagens')),
]

passagens/models.py
from django.db import models

# Create your models here.

passagens/forms.py
from django import forms
from .validation import *
from tempus_dominus.widgets import DatePicker


class PassagemForm(forms.Form):
    origem = forms.CharField(label='Origem', max_length=100)
    destino = forms.CharField(label='Destino', max_length=100)
    data_ida = forms.DateField(label='Ida', widget=DatePicker())
    data_retorno = forms.DateField(label='Volta', widget=DatePicker())

    def clean(self):
        origem = self.cleaned_data.get('origem')
        destino = self.cleaned_data.get('destino')
        data_ida = self.cleaned_data.get('data_ida')
        data_retorno = self.cleaned_data.get('data_retorno')

        lista_de_erros = {}

        verifica_se_inputs_contem_numeros(origem, 'origem', lista_de_erros)
        verifica_se_inputs_contem_numeros(destino, 'destino', lista_de_erros)
        verifica_se_origem_e_igual_ao_destino(origem, destino, lista_de_erros)
        verifica_data_ida_maior_data_volta(data_ida, data_retorno, lista_de_erros)
        verifica_data_ida_nao_pode_ser_maior_que_data_de_hoje(data_ida, lista_de_erros)

        if lista_de_erros is not None:
            for erro in lista_de_erros:
                mensagem = lista_de_erros[erro]
                self.add_error(erro, mensagem)
        return self.cleaned_data

passagens/views.py
from django.shortcuts import render
from passagens.forms import PassagemForm


def index(request):
    form = PassagemForm
    context = {'form': form}
    return render(request, 'home.html', context)


def detalhes(request):
    if request.method == 'POST':
        form = PassagemForm(request.POST)
        if form.is_valid():
            context = {'form': form}
            return render(request, 'detalhes.html', context)
        return render(request, 'home.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    {{ form.media }}
    <title>Validando Formulários</title>
</head>
<body>

{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

templates/detalhes.html
{% extends 'base.html' %}>
{% block content %}
    <div class="mx-auto p-5">
        <ul>
            <li>
                Origem: {{ form.origem.value }}
            </li>
            <li>
                Destino: {{ form.destino.value }}
            </li>
            <li>
                Data de Ida: {{ form.data_ida.value }}
            </li>
            <li>
                Data de retorno: {{ form.data_retorno.value }}
            </li>
        </ul>
    </div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="mx-auto p-5 col-8">
        <form method="POST" action="{% url 'passagens:detalhes' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <ul>
                {% for erros in fields.erros %}
                    <li>
                        {{ fields.erros }}
                    </li>
                {% endfor %}
            </ul>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
{% endblock content %}